### ISSUE TITLE
[Request] CombatLogger 

### ISSUE THREAD

**Issue by Mostro96** [PocketMineItalianDevs/Request#8]
### Descrizione del Plugin / Plugin description
- _Cosa dovrebbe fare il plugin?_
 
Evitare ai player di fare certi comandi quando sono in combattimento

### Terze Parti

- _Esistono altri plugin che fanno ciò che ci chiedi?_ 
   - [x] Si
   - [ ] No
- _Se si, perché vorresti che lo rifacessimo?_

Perchè ha un bug penose che se metti lo spazzio dopo li / ti fa eseguire lo stesso il comando anche se bannato esempio / spawn e ti tippa lo stesso allo spawn

- Il plugin in questione supporta l'ultima api di pocketmine? 
   - [x] Si
   - [ ] No

### Utilità

- _Credi che il plugin sia utile alla community?_
   - [x] Si
   - [ ] No
- _Se si, perché? Esponi dettagliatamente le tue motivazioni:_
Perchè l'originale è molto buggato
  

### Contatti

- _Hai un social media, quali Telegram e Twitter dove ci è possibile contattarti per ulteriori chiarimenti?_ 
   - _Telegram:_ https://t.me/Medusq

**Comment by RubyTemple** [comment]
https://github.com/PocketMineItalianDevs/PocketMine-Plugins/tree/master/CombatLogger
